name: Test IPv6 literal

on: workflow_dispatch

jobs:
  ipv6:
    runs-on: ubuntu-22.04
    if: always()
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npx start-server-and-test start http://localhost:3000 cy:run

  ipv6-debug:
    runs-on: ubuntu-22.04
    if: always()
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npx start-server-and-test start http://localhost:3000 cy:run
      env:
        DEBUG: cypress:*

  ipv6-debug-network:
    runs-on: ubuntu-22.04
    if: always()
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npx start-server-and-test start http://localhost:3000 cy:run
      env:
        DEBUG: 'cypress:network:*,cypress:server:remote-states'
